difftastic broke here i have no idea what changed
thread'main'panicked at src/display/hunks.rs:517:17：
internal error:entered unreachable code: Should be impossible: every LHS
Unchanged MatchedPos should have a corresponding
RHS Unchanged MatchedPos
None
Some（MatchedPos ｛ kind:UnchangedToken ｛ highlight:Delimiter,self_pos：
［SingleLineSpan ｛ Line: LineNumber:7（zero-
indexed: 6），start_col: 0,end_col: 1 ｝］，opposite-pos： ［SingleLineSpan ｛
Line: LineNumber:7 （zero-indexed: 6），
start_col: 0,end_col: 1 ｝］ ｝， pos: SingleLineSpan ｛ line: LineNumber:7
（zero-indexed: 6），start_col: 0,end-col: 1｝｝）
note:run with'RUST_BACKTRACE=1°environment variable to display a
backtrace
fatal:external diff died, stopping at app/blog/page.tsx